/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ListingType = { 'buy' : null } |
  { 'rent' : null };
export interface Property {
  'id' : bigint,
  'title' : string,
  'postedAt' : bigint,
  'postedBy' : Principal,
  'contactName' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'city' : string,
  'description' : string,
  'isActive' : boolean,
  'listingType' : ListingType,
  'state' : string,
  'areaSqFt' : bigint,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : string,
  'contactPhone' : string,
}
export type PropertyType = { 'commercial' : null } |
  { 'villa' : null } |
  { 'plot' : null } |
  { 'apartment' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProperty' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      PropertyType,
      ListingType,
      bigint,
      bigint,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProperties' : ActorMethod<[], Array<Property>>,
  'getProperties' : ActorMethod<
    [
      [] | [string],
      [] | [ListingType],
      [] | [PropertyType],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Property>
  >,
  'getProperty' : ActorMethod<[bigint], Property>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProperty' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      PropertyType,
      ListingType,
      bigint,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];