/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'villa' : IDL.Null,
  'plot' : IDL.Null,
  'apartment' : IDL.Null,
});
export const ListingType = IDL.Variant({ 'buy' : IDL.Null, 'rent' : IDL.Null });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'postedBy' : IDL.Principal,
  'contactName' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'city' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'listingType' : ListingType,
  'state' : IDL.Text,
  'areaSqFt' : IDL.Nat,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PropertyType,
        ListingType,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperties' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(ListingType),
        IDL.Opt(PropertyType),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProperty' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PropertyType,
        ListingType,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'villa' : IDL.Null,
    'plot' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const ListingType = IDL.Variant({ 'buy' : IDL.Null, 'rent' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'postedBy' : IDL.Principal,
    'contactName' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'city' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'listingType' : ListingType,
    'state' : IDL.Text,
    'areaSqFt' : IDL.Nat,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PropertyType,
          ListingType,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperties' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(ListingType),
          IDL.Opt(PropertyType),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProperty' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PropertyType,
          ListingType,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };